<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Newsletter $block */
?>
<?= $block->getChildHtml('form_before') ?>
    <form class="form form-newsletter-manage" action="<?= $block->escapeUrl($block->getAction()) ?>" method="post" id="form-validate">
        <fieldset class="fieldset">
            <?= $block->getBlockHtml('formkey') ?>
			<div class="heade" style="background-color:#e8e8e8;">
				<h3 class="legend" style="text-align: center; padding-top: 25px;">
					<span>Stay in the know and NEVER miss a bargain again.<br> Signup for emails to get scope on new products and hot deals</span>
				</h3><br>
			</div>
			<br><br><br>
            <div class="field choice" style="margin-left: -30%!important;">
                <input type="checkbox" name="is_subscribed" id="subscription" value="1" title="<?= $block->escapeHtmlAttr(__('General Subscription')) ?>"<?php if ($block->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox">
                <label for="subscription" class="label"><span><?= $block->escapeHtml(__('Tick here & click Save to join')) ?></span></label>
            </div>
            <?php /* Extensions placeholder */ ?>
            <?= $block->getChildHtml('customer.form.newsletter.extra') ?>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary"><button type="submit" title="<?= $block->escapeHtmlAttr(__('Save')) ?>" class="action save primary"><span><?= $block->escapeHtml(__('Save')) ?></span></button></div>
            <div class="secondary" style="margin-left: -30%!important;"><a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>"><button type="submit"<span><?= $block->escapeHtml(__('Back')) ?></span></button></a></div>
        </div>
    </form>
<?php /* Extensions placeholder */ ?>
<?= $block->getChildHtml('customer.form.newsletter.extra2') ?>
