<!DOCTYPE HTML>
<!--[if lt IE 7 ]>
<html lang="en" class="ie ie6"> <![endif]-->
<!--[if IE 7 ]>
<html lang="en" class="ie ie7"> <![endif]-->
<!--[if IE 8 ]>
<html lang="en" class="ie ie8"> <![endif]-->
<!--[if IE 9 ]>
<html lang="en" class="ie ie9"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <title><?php echo $this->getStaticBlockTitle(); ?></title>
        <meta name="description" content="Site Under Maintenance">
        <meta http-equiv="X-UA-Compatible" content="chrome=1">
        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->getFavicon(); ?>">

        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=PT+Sans+Narrow:regular,bold">
        <link rel="stylesheet" type="text/css" href="<?php echo $this->getAsset('css/styles.css'); ?>">
    </head>

    <body id="home">
        <div id="Header">
            <div class="wrapper">
                <h1><?php echo $this->getHeaderTitle(); ?></h1>
            </div>
        </div>
        <div id="Content" class="wrapper">
            <?php if ($this->getHelper()->hasCountdown()) : ?>
                <div class="countdown styled"></div>
            <?php endif; ?>

            <?php echo $this->getChildHtml($this->getStaticPageIdentifier()); ?>
            <?php $subscriptionLinks = $this->getSubsciptionLinks(); ?>
            <?php if (!empty($subscriptionLinks)) : ?>
                <div id="subscribe">
                    <div id="socialIcons">
                        <ul>
                            <?php foreach ($subscriptionLinks as $linkKey => $linkValue) : ?>
                                <li><a href="<?php echo $linkValue; ?>" target="_blank" title="<?php echo ucfirst($linkKey); ?>" class="<?php echo $linkKey; ?>Icon"></a></li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
            <?php endif; ?>
        </div>

        <div id="overlay"></div>

        <!--Scripts-->
        <script type="text/javascript" src="<?php echo $this->getAsset('js/jquery-1.9.1.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->getAsset('js/Backstretch.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->getAsset('js/jquery.countdown.js'); ?>"></script>

        <script type="text/javascript">
            $(function () {
                $.backstretch('<?php echo $this->getBackgroundImage('images/image1.jpg'); ?>');

<?php if ($this->getHelper()->hasCountdown()) : ?>
                    var endDate = "<?php echo date('Y-m-d H:i:s', strtotime($this->getHelper()->getConfig('MaintenanceMode/Configuration/upDateTime'))); ?>";

                    $('.countdown.simple').countdown({date: endDate});

                    $('.countdown.styled').countdown({
                        date: endDate,
                        render: function (data) {
                            $(this.el).html("<div>" + data.days + " <span><?php echo __('days'); ?></span></div><div>" + data.hours + " <span><?php echo __('hrs'); ?></span></div><div>" + data.min + " <span><?php echo __('min'); ?></span></div><div>" + data.sec + " <span><?php echo __('sec'); ?></span></div>");
                        }
                    });
<?php endif; ?>
            });
        </script>
    </body>
</html>