<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Shopping cart template
 *
 * @var $block \Magento\Checkout\Block\Cart
 */

if ($block->getItemsCount()) {
    echo $block->getChildHtml('with-items');
} else {
    echo $block->getChildHtml('no-items');
}
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_helper = $_objectManager->create('\Serole\Sage\Helper\Data');
$errorSkus = $_helper->getValue();
if(isset($errorSkus) && $errorSkus != '')
{
	echo "<script>onload = alert('Some products in cart are out of stock.')</script>";
	$_helper->unSetValue();
}