#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

#login:
#    path: /user/login
#    controller: App\Controller\UserController::userLogin