<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
$title = '';
if (trim($block->getPageHeading())) {
    $title = '<span class="base" data-ui-id="page-title-wrapper" ' .  $block->getAddBaseAttribute() . '>'
        . $block->escapeHtml($block->getPageHeading()) . '</span>';
}
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$handle = $objectManager->create('\Magento\Framework\App\Action\Context');
	$module_name     = $handle->getRequest()->getModuleName();
    $controller_name = $handle->getRequest()->getControllerName();
    $action_name     = $handle->getRequest()->getActionName();
	$urlChk=$module_name.'/'.$controller_name.'/'.$action_name;
	$customTitle="";
	if($urlChk=='helpdesk/ticket/create'){$customTitle="Create Enquiry";}
?>

<?php if ($title): ?>
<div class="page-title-wrapper<?= /* @escapeNotVerified */ $cssClass ?>">
    <h1 class="page-title"
        <?php if ($block->getId()): ?> id="<?= /* @escapeNotVerified */ $block->getId() ?>" <?php endif; ?>
        <?php if ($block->getAddBaseAttributeAria()): ?>
            aria-labelledby="<?= /* @escapeNotVerified */ $block->getAddBaseAttributeAria() ?>"
        <?php endif; ?>>
        <?php if ($customTitle==''){?>
			<?= /* @escapeNotVerified */ $title ?>
        <?php }elseif($customTitle!=''){?>
			<?= /* @escapeNotVerified */ $customTitle; ?>
        <?php }?>
    </h1>
    <?= $block->getChildHtml() ?>
</div>
<?php endif; ?>



