<?php
$priceModel = $block->getPriceType('regular_price');
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
$color = $this->helper('Serole\Productprice\Helper\Data')->getConfig('theme_design/colors/color');
$commingsoon_status = $block->getSaleableItem()->getComingSoon();
$commingsoon_text = $block->getSaleableItem()->getComingSoonText();
?>
<style>
.base .price-container .price-label{color:<?php echo $color; ?> !important;}
.base .price-container .price-wrapper .price{color:<?php echo $color; ?> !important;}
.esab {text-decoration:line-through!important;}
</style>
<?php 	
	if($commingsoon_status==1 && $commingsoon_text!=''){
		$class_status='display:none';
		$commingsoon_text;
	}else{
		$class_status='';
		$commingsoon_text='';
	}
?>
<span style="<?php echo $class_status;?>">
<?php if ($block->hasSpecialPrice()): ?>
	<span class="special-price">
        <?php  echo $block->renderAmount($finalPriceModel->getAmount(), [
            'display_label' 	=> __('Special Price'),
            'price_id'      	=> $block->getPriceId('product-price-' . $idSuffix),
    	    'price_type'    	=> 'finalPrice',
            'include_container' => true,
            'schema' => $schema
    	]); ?>
    </span>
	<span class="base esab" style="color:<?php echo $color; ?>">
        <?php  echo $block->renderAmount($priceModel->getAmount(), [
        	'display_label' 	=> __('Regular Price'),
            'price_id'      	=> $block->getPriceId('old-price-' . $idSuffix),
            'price_type'    	=> 'oldPrice',
            'include_container' => true,
            'skip_adjustments'  => true
	    ]); ?>
    </span>
	<span class="special-price">
	<?php
	$item = $block->getSaleableItem();
    //$_savePercent = 100 - round(((float)$item->getFinalPrice() / (float)$item->getPrice()) * 100);
	$_savePercent = number_format($item->getPrice()-$item->getFinalPrice(),2) ;
	if($_savePercent > 0)
	  echo '<span class="price-label">Save</span><span> <b style="color:#EA4335;">$'.$_savePercent . ' </b><span>'; 
	?>
    </span>
<?php else: ?>
    <?php  echo $block->renderAmount($finalPriceModel->getAmount(), [
        'price_id'      	=> $block->getPriceId('product-price-' . $idSuffix),
        'price_type'    	=> 'finalPrice',
        'include_container' => true,
    	'schema' => $schema
	]); ?>
<?php endif; ?>
 
<?php if ($block->showMinimalPrice()): ?>
	<?php if ($block->getUseLinkForAsLowAs()):?>
    	<a href="<?=  $block->getSaleableItem()->getProductUrl() ?>" class="minimal-price-link">
            <?= $block->renderAmountMinimal() ?>
        </a>
	<?php else:?>
    	<span class="minimal-price-link">
            <?=  $block->renderAmountMinimal() ?>
        </span>
	<?php endif?>
<?php endif; ?>
</span>