<?php
/*
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$mediaUrl = $objectManager->get('Magento\Store\Model\StoreManagerInterface')
                    ->getStore()
                    ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
*/
$custOrders = $this->getAllOrders(); 
?>
<!--<img src="<?php //echo $mediaUrl;?>dashboard.png" />-->
<style>
#customers {
  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #33424D;
  color: white;
}
</style>
<table id="customers">
  <tr>
    <th>Merchant</th>
    <th>Order Id</th>
    <th>Ship To</th>
	<th>Bill To</th>
	<th>Products</th>
	<th>Order Total</th>
	<th>Erned Points</th>
	<th>Date</th>
  </tr>
 <?php 
    foreach($custOrders as $custOrder) { 
	  $custOrderData = $custOrder->getData();
	  $imgUrl = $this->getImgUrl($custOrderData['merchant_id']);
?>
  <tr>
    <td><img src="<?php echo $imgUrl; ?>" /></td>
    <td><?php echo $custOrderData['order_id']; ?></td>
	<td><?php echo $custOrderData['ship_to']; ?></td>
	<td><?php echo $custOrderData['bill_to']; ?></td>
	<td><?php echo $custOrderData['products']; ?></td>
	<td><?php echo $custOrderData['order_total']; ?></td>
	<td><?php echo $custOrderData['rewards_points']; ?></td>
	<td><?php echo date("Y-m-d", strtotime($custOrderData['created_at'])); ?></td>
  </tr>
<?php
  }
?>
</table>