<?php
/*
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$mediaUrl = $objectManager->get('Magento\Store\Model\StoreManagerInterface')
                    ->getStore()
                    ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
*/
$usedPoints = $this->getAllUsedDetails(); 
?>
<!--<img src="<?php //echo $mediaUrl;?>dashboard.png" />-->
<style>
#customers {
  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #33424D;
  color: white;
}
</style>
<table id="customers">
  <tr>
    <th>Web Order Id</th>
    <th>Order Total</th>
    <th>Used Points</th>
	<th>Date</th>
  </tr>
 <?php 
    foreach($usedPoints as $custOrder) { 
	  $custOrderData = $custOrder->getData();
	  $entityId = $this->getOrderEntityId($custOrderData['order_id']);
?>
  <tr>

    <td><a style="text-decoration:underline;" href="/rac_demo/sales/order/view/order_id/<?php echo $entityId ?>/"><?php echo $custOrderData['order_id']; ?></a></td>
	<td><?php echo $custOrderData['order_total']; ?></td>
	<td><?php echo $custOrderData['used_points']; ?></td>
	<td><?php echo date("Y-m-d", strtotime($custOrderData['created_at'])); ?></td>
  </tr>
<?php
  }
?>
</table>