<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
$title = '';
if (trim($block->getPageHeading())) {
    $title = '<span class="base" data-ui-id="page-title-wrapper" ' .  $block->getAddBaseAttribute() . '>'
        . $block->escapeHtml($block->getPageHeading()) . '</span>';
}
?>
<?php
 if ($title): 
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        
$storeManager  = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeCode     = $storeManager->getStore()->getCode();

$request = $objectManager->get('Magento\Framework\App\Action\Context')->getRequest();
$currentPage = $request->getFullActionName();

if($storeCode=='mydiscounts' && $currentPage=='customer_account_login'){
	$mydiscountTittle=$block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('Mydiscount-Account-Login')->toHtml();
	$title=$mydiscountTittle;
}elseif($storeCode=='mydiscounts' && $currentPage=='customer_account_create'){
	$mydiscountTittle=$block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('Mydiscount-Account-Register')->toHtml();
	$title=$mydiscountTittle;
}elseif(($storeCode=='charlies'||$storeCode=='whittlesea'||$storeCode=='neatclubs'||$storeCode=='acorns') && $currentPage=='customer_account_login'){
		$Tittle=$block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('Account-Login-Stores')->toHtml();
		$title=$Tittle;
}elseif(($storeCode=='kmartrewards_en') && $currentPage=='customer_account_login'){
		$Tittle=$block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('Account-Login-Kmartrewards')->toHtml();
		$title=$Tittle;
}else{
	if($storeCode!='mydiscounts' && $currentPage=='customer_account_login'){
		$mydiscountTittle=$block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('Account-Login')->toHtml();
		$title=$mydiscountTittle;
	}	
	if($storeCode!='mydiscounts' && $currentPage=='customer_account_create'){
		$mydiscountTittle=$block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('Account-Register')->toHtml();
		$title=$mydiscountTittle;
	}
}	
?>
<div class="page-title-wrapper<?= /* @escapeNotVerified */ $cssClass ?>">
    <h1 class="page-title"
        <?php if ($block->getId()): ?> id="<?= /* @escapeNotVerified */ $block->getId() ?>" <?php endif; ?>
        <?php if ($block->getAddBaseAttributeAria()): ?>
            aria-labelledby="<?= /* @escapeNotVerified */ $block->getAddBaseAttributeAria() ?>"
        <?php endif; ?>>
        <?= /* @escapeNotVerified */ $title ?>
    </h1>
    <?= $block->getChildHtml() ?>
</div>
<?php endif; ?>
