<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login\Info $block */
?>
<?php 
	$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        
	$storeManager  = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
	$storeName     = $storeManager->getStore()->getName();
	$storeCode     = $storeManager->getStore()->getCode();
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
<div class="block block-new-customer">
    <div class="block-title">
        
    </div>
    <div class="block-content" aria-labelledby="block-new-customer-heading">
		<strong id="block-new-customer-heading" class="new-user" role="heading" aria-level="2"><?= $block->escapeHtml(__('New Users')) ?></strong>
        <p>
		<?php if($storeCode=='kmartrewards_en'){?>
			<p>To access this website you need a valid login.</p>
			<p>This can only be assigned by a website administrator.</p>
			<p>In order to request a login please contact Neat Ideas either: <br>
			 By Phone on <strong>08 6389 0055</strong>
			 <br> or by email at <a href="mailto:customersupport@neatideas.com.au">customersupport@neatideas.com.au</a>
			</p>  
		<?php }?>
		<?php if($storeCode=='neatclubs'){?>
			<span>If you're looking to have your business or social club join <strong>Neat Ideas Clubs</strong> all you need to do is <a href="mailto:sales@neatideas.com.au">contact us</a> and we'll go through the registration process with you.</span> 
		<?php }else{?>
		<?= $block->escapeHtml(__('To use the '.$storeName.', you will need to register a new account.
		It only takes a minute and once you are registered you will have unlimited access to a huge collection of tickets and offers, you will be able to view and track your orders and more.')) ?></p>
		<?php }?>
		<div class="block-title bottom-line-cust"></div>
		<div class="actions-toolbar btn-rgtr-cust">
			<div class="primary">
				<a href="<?= $block->escapeUrl($block->getCreateAccountUrl()) ?>" class="action create primary"><span><?= $block->escapeHtml(__('Register a new Account')) ?></span></a>
			</div>
		</div>
    </div>
</div>
<?php endif; ?>
  