<?php
/**
 * @var \MagePsycho\RedirectPro\Block\Adminhtml\System\Config\Form\Field\ManualContent $block
 */
?>
<style>
   .manual-popup code {
        padding: 2px 4px;
        margin: 0;
        border-radius: 3px;
        word-wrap: break-word;
        background-color: #F1F1F1;
        font-family: Monaco, Menlo, Consolas, "Courier New", monospace;
        font-size: 14px;
    }
</style>
<script type="text/x-magento-init">
{
    "*": {
        "magepsychoRedirectProManual": <?php echo $block->getContent(); ?>
    }
}
</script>